# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.6.10
_src_path: gh:dafyddj/copier-docker-build
container_registry: ghcr.io
image_authors: DJ
image_namespace: dafyddj
image_repo: tmp-renovate
