# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
#    -   id: trailing-whitespace
#    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: ^kitchen.yml$
    -   id: check-added-large-files
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0.3
    hooks:
      - id: hadolint
        name: Check Dockerfiles with hadolint
        args: [--failure-threshold, error]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.3
    hooks:
      - id: check-renovate
        name: Check Renovate config with check-jsonschema
        args: ["--verbose"]
  - repo: https://github.com/rubocop-hq/rubocop
    rev: v1.57.0
    hooks:
      - id: rubocop
        name: Check Ruby files with rubocop
        args: [--debug]
