---
name: Main
on:
  push:
  pull_request:
  schedule:
    - cron: 14 15 * * *

env:
  # renovate: datasource=github-tags depName=saltstack/salt extractVersion=^v(?<version>.*)$
  SALT_VERSION: "3006.7"

jobs:
  pre-commit:
    name: Run `pre-commit`
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
  gsv:
    name: Get Salt versions
    runs-on: ubuntu-latest
    outputs:
      salt-versions: ${{ steps.get-salt-versions.outputs.salt-versions }}
    steps:
      - id: get-salt-versions
        uses: dafyddj/get-salt-versions@facbecc73d55759ff6940c48e22dfa52e6e74f63 # v2.13.0
  test:
    name: Test this action
    needs: gsv
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        salt-version: ${{ env.SALT_VERSION }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Run this action
        uses: ./
        with:
          salt-version: ${{ matrix.salt-version }}
          custom-config: |
            test_key1: test_value1
            test_key2: test_value2
      - name: Verify Salt version installed
        env:
          SALT_VER_EXPECTED: ${{ matrix.salt-version }}
        run: |
          $SALT_VER_INSTALLED = (-split $(salt-call --version))[1]
          if ($SALT_VER_INSTALLED -ne $env:SALT_VER_EXPECTED) {
              exit 1
          }
      - name: Verify custom config
        run: |
          foreach ($i in 1..2) {
              $value = salt-call config.get "test_key$i" --out newline_values_only
              if ($value -ne "test_value$i") {
                  exit 1
              }
          }
  release:
    name: Release
    needs:
      - pre-commit
      - test
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Run `semantic-release`
        uses: codfish/semantic-release-action@cbd853afe12037afb1306caca9d6b1ab6a58cf2a # v1.10.0
        id: sem-rel
        with:
          branches: |
            ["main"]
          plugins: |
            [ "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/github"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update branch for major version
        if: steps.sem-rel.outputs.new-release-published == 'true'
        run: git push
             https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
             HEAD:refs/heads/v${{steps.sem-rel.outputs.release-major}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Healthchecks.io
        if: github.ref == 'refs/heads/main'
        run: curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/${HC_UUID}
        env:
          HC_UUID: ${{ secrets.HC_UUID }}
