---
name: Renovate

on:
  push:
    branches:
      - '**'
    paths:
      - .copier-answers.yml
  workflow_dispatch:

jobs:
  renovate:
    name: Run self-hosted
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@063e0c946b9c1af35ef3450efc44114925d6e8e6 # v40.1.11
        with:
          configurationFile: .github/copier-renovate.json5
          docker-cmd-file: .github/entrypoint.sh
          docker-user: root
          token: ${{ steps.app-token.outputs.token }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
